import "./globals.scss";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import AppContext from "@/context/AppContext";

const roboto = Roboto({ weight: ["300", "400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppContext>{children}</AppContext>
      </body>
    </html>
  );
}
